---
apiVersion: v1
kind: Service
metadata:
  name: mbbank-web-service
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 3006
  selector:
    app: mbbank-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbbank-web
  labels:
    app: mbbank-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mbbank-web
    spec:
      containers:
      - name: mbbank-web
        image: {{IMAGE}}
        ports:
          - containerPort: 3006
  selector:
    matchLabels:
      app: mbbank-web
